---
version: '3.1'

services:
 
  db:
    image: mysql:8
    ports:
      - "3309:3306"
    volumes:
      - data:/dbmysql
      - mysql-datadir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=employee
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Europe/Berlin
      
  employee-service:
    depends_on:
      - 'db'
    ports: 
      - "8080:8080"
    build:
      context: ./employee-service/
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      
volumes:
  data:
  mysql-datadir:

