logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  forward-headers-strategy: framework
spring:
  datasource:
    password: root
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/employee
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.
    open-in-view: false
  flyway:
    locations: db/migration
    baselineOnMigrate: true

security:
  jwt:
    expiration-time: 86400000
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b